### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by Jcomper** [guillotinaweb/ngx-schema-form#326]
IE 11 is not supported as far as I can tell.
Dependency jexl is using ES6 class syntax, after transpiling it to ES5 I faced a problem that Proxy object is used in formproperty.ts 
`  set properties(properties: FormProperty[] | { [key: string]: FormProperty }) {
    /**
     * Override the setter to add an observer that notices when an item is added or removed.<br/>
     */
    this._properties = new Proxy(properties, this._propertyProxyHandler);
  }`

and there is no Proxy Polyfill for IE11.

Any thoughts on this?

**Comment by ebrehault** [comment]
Sorry, but currently, we have no plan about IE11 support.
Of course, if you come up with a pull request providing IE11 support and not impacting negatively the current implementation, we would definitely merge it.

**Comment by akshaygolash** [comment]
@Jcomper - Are you planning yo create PR ? My angular app also does not compile in IE 11 because of JEXL not providing es5 transpiled code.

**Comment by daniele-pecora** [comment]
Jexl ES5 support pull request is already there:
https://github.com/TomFrost/Jexl/issues/57

**Comment by daniele-pecora** [comment]
Jexl ES5 support pull request has been merged and released as version 2.3.0
https://github.com/TomFrost/Jexl#57
https://github.com/TomFrost/Jexl/pull/87

**Comment by rodrigo-vizbelis** [comment]
Hi @daniele-pecora . I tried your suggested solution but it doesn't work with latest ngx-schema-form@2.5.7 and also ngx-schema-form@2.5.0

IE11 error messages:
- version 2.5.7: "Proxy polyfill does not support trap 'logger'"
- version 2.5.0: "Proxy polyfill does not support trap 'deleteProperty'"

**Comment by daniele-pecora** [comment]
Hi @rodrigo-vizbelis could you try this version I build here:
[ngx-schema-form-2.5.7-beta.1.tgz.zip](https://github.com/guillotinaweb/ngx-schema-form/files/5294670/ngx-schema-form-2.5.7-beta.1.tgz.zip)

Just extract the ZIP file somewhere and install via path like 
`$ npm install ./myfolder/ngx-schema-form-2.5.7-beta.1.tgz`

**Comment by rodrigo-vizbelis** [comment]
@daniele-pecora ExtendedProxyHandler changes solves issue about proxy polyfill unsupported traps. Here is a stack trace from new IE11 issue:

```
stack: "TypeError: Cannot create property for a non-extensible object
   at createProperties (http://localhost:4200/vendor.js:167489:11)
   at ObjectProperty (http://localhost:4200/vendor.js:167447:5)
   at PROPERTY_TYPE_MAPPING.object (http://localhost:4200/vendor.js:167538:3)
   at createProperty (http://localhost:4200/vendor.js:165679:13)
   at ngOnChanges (http://localhost:4200/vendor.js:166820:9)
   at rememberChangeHistoryAndInvokeOnChangesHook (http://localhost:4200/vendor.js:36929:5)
   at callHook (http://localhost:4200/vendor.js:38024:5)
   at callHooks (http://localhost:4200/vendor.js:37981:9)
   at executeInitAndCheckHooks (http://localhost:4200/vendor.js:37919:5)
   at selectIndexInternal (http://localhost:4200/vendor.js:41849:9)"
   }
```
Error comes from ObjectProperty class line 55:

`this.properties[propertyId] = this.formPropertyFactory.createProperty(propertySchema, this, propertyId);`

**Comment by daniele-pecora** [comment]
@rodrigo-vizbelis 

The [GoogleChrome/proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill/blob/master/src/proxy.js) does make the wrapped object immutable by calling `Object.seal(...)` on them.
That is why adding new properties wont work here.

As I see there is another proxy polyfill [es6-proxy-polyfill](https://github.com/ambit-tsai/es6-proxy-polyfill) which does not `seal` the target and proxied objects.

Would you like try it out?

**Comment by erlioniel** [comment]
@daniele-pecora I think the label on the issue is misleading. Maybe remove it?

I was trying to play with polyfills, but didn't manage to make it working. So rolled back to 3.5.x :(
